# -*- coding: utf-8 -*-
"""Practical 2 nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kNcxHZqTl3_L0I3JSdWXs-DfSWD0x893
"""

!python -m spacy download en_core_web_lg

import spacy
nlp = spacy.load("en_core_web_lg")

import pandas as pd

df = pd.read_json('/content/news_dataset.json')

print(df.shape)

df.head()

df['category'].value_counts()

df['label_num'] = df['category'].map({'CRIME':0, 'SPORTS': 1, 'BUSINESS': 2, 'SCIENCE':3})

df.head(5)

def preprocess(text):
  doc = nlp(text)
  filtered_tokens = []
  for token in doc:
    if token.is_stop or token.is_punct:
      continue
    filtered_tokens.append(token.lemma_)
  return ' '.join(filtered_tokens)

df['preprocessed_text'] = df['text'].apply(lambda text: preprocess(text))

df.head()

"""**Train Test Split**"""

from sklearn.model_selection import train_test_split
import numpy as np

# Create the 'vector' column by applying the nlp model to the 'preprocessed_text'
# This generates a vector representation for each preprocessed text entry.
df['vector'] = df['preprocessed_text'].apply(lambda text: nlp(text).vector)

# Stack the 1D numpy arrays (vectors) into a single 2D numpy array.
# This is necessary because train_test_split expects X to be a 2D array (samples x features).
X = np.stack(df['vector'].values)

# Perform the train-test split
X_train, x_test, y_train, y_test = train_test_split(
    X, # Use the correctly stacked 2D array for features
    df.label_num,
    test_size=0.2,
    random_state=2022,
    stratify=df.label_num
)

import numpy as np

print("Shape of X_train before reshaping: ", X_train.shape)
print("Shape of x_test before reshaping: ", x_test.shape)

X_train_2d = np.stack(X_train)
x_test_2d =  np.stack(x_test)

print("Shape of X_train after reshaping:", X_train_2d.shape)
print("Shape of x_test after reshaping:", x_test_2d.shape)

"""**Attempt 1**"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report # Import the correct function

clf = DecisionTreeClassifier()
clf.fit(X_train_2d, y_train)
y_pred = clf.predict(x_test_2d)
print(classification_report(y_test,y_pred)) # Corrected function name

"""**Attempt 2**"""

from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

scaler = MinMaxScaler()
scaled_train_embed = scaler.fit_transform(X_train_2d)
scaled_test_embed = scaler.transform(x_test_2d)

clf = MultinomialNB()
clf.fit(scaled_train_embed, y_train)
y_pred = clf.predict(scaled_test_embed)

print(classification_report(y_test,y_pred))

"""**Attempt 3**"""



"""**Attempt 4**"""



"""**Attempt 5**"""

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report

clf = GradientBoostingClassifier()
clf.fit(X_train_2d, y_train)
y_pred = clf.predict(x_test_2d)
print(classification_report(y_test,y_pred))

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

from matplotlib import pyplot as plt
import seaborn as sns
sns.heatmap(cm, annot=True, fmt='g')
plt.figure(figsize = (10,7))
plt.show()
plt.xlabel('Predicted')
plt.ylabel('Truth')

