# -*- coding: utf-8 -*-
"""Practical No1 Nlp.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tIlW0OFe20qmaW91shegzwe2kR9j7j3G
"""

import pandas as pd

#read the dataset with name "Fake_Real_Data.csv" and storeit in a variable df
df = pd.read_csv("Fake_Real_Data.csv")

#displaying the first 10 elements of the dataset
df.head(5)

#print the shape of the dataframe
print(df.shape)

df.head(5)

#check the distribution of labels
df['label'].value_counts()

#Add the bew column which gives a  unique number  to each of these labels
df['label_num']= df['label'].map({'Fake':0,'Real':1})

df.head(5)

!python -m spacy download en_core_web_lg

import spacy
nlp = spacy.load("en_core_web_lg")

df['vector']=df['Text'].apply(lambda text: nlp(text).vector)

from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(df['vector'].values,df['label_num'],test_size=0.2,random_state=2022)

import numpy as np

X_train_2d = np.stack(X_train)
X_test_2d = np.stack(X_test)

from sklearn.naive_bayes import MultinomialNB
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

scaler = MinMaxScaler()
scaled_train_embed =  scaler.fit_transform(X_train_2d)
scaled_test_embed = scaler.transform(X_test_2d)

clf = MultinomialNB()
clf.fit(scaled_train_embed,y_train)

y_pred = clf.predict(scaled_test_embed)
print(classification_report(y_test,y_pred))

from sklearn.neighbors import KNeighborsClassifier

#1 creating  a KNN Model
clf = KNeighborsClassifier(n_neighbors=5, metric = 'euclidean')

#2 Fit with all _Train _embeddings and y_train
clf.fit(X_train_2d, y_train)

#3 get the predictions for all_test_embeddings and store it in y_pred
y_pred = clf.predict(X_test_2d)

#4 Classification Report
print(classification_report (y_test, y_pred))

"""**Confusion Report**"""

#finslly print the confusion matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

from matplotlib import pyplot as plt
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Prediction')
plt.ylabel('Truth')

